// <auto-generated />
using System;
using MP.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MP.Core.Sqlite.Migrations
{
    [DbContext(typeof(MPContext))]
    [Migration("20200825222404_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("MP.Core.Models.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("MP.Core.Models.AudioStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BitRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelLayout")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodecLongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodecName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaFormatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SampleRateHz")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("MediaFormatId");

                    b.ToTable("AudioStreams");
                });

            modelBuilder.Entity("MP.Core.Models.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileExt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("MP.Core.Models.MediaFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<double>("BitRate")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormatLongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProbeScore")
                        .HasColumnType("REAL");

                    b.Property<int>("StreamCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId")
                        .IsUnique();

                    b.ToTable("MediaFormats");
                });

            modelBuilder.Entity("MP.Core.Models.VideoStream", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<double>("AvgFrameRate")
                        .HasColumnType("REAL");

                    b.Property<int>("BitRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BitsPerRawSample")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodecLongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodecName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayAspectRatio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<double>("FrameRate")
                        .HasColumnType("REAL");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MediaFormatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PixelFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("MediaFormatId");

                    b.ToTable("VideoStreams");
                });

            modelBuilder.Entity("MP.Core.Models.Analysis", b =>
                {
                    b.HasOne("MP.Core.Models.MediaFile", "File")
                        .WithOne("Analysis")
                        .HasForeignKey("MP.Core.Models.Analysis", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MP.Core.Models.AudioStream", b =>
                {
                    b.HasOne("MP.Core.Models.Analysis", "Analysis")
                        .WithMany("AudioStreams")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MP.Core.Models.MediaFormat", null)
                        .WithMany("AudioStreams")
                        .HasForeignKey("MediaFormatId");
                });

            modelBuilder.Entity("MP.Core.Models.MediaFormat", b =>
                {
                    b.HasOne("MP.Core.Models.Analysis", "Analysis")
                        .WithOne("Format")
                        .HasForeignKey("MP.Core.Models.MediaFormat", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MP.Core.Models.VideoStream", b =>
                {
                    b.HasOne("MP.Core.Models.Analysis", "Analysis")
                        .WithMany("VideoStreams")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MP.Core.Models.MediaFormat", null)
                        .WithMany("VideoStreams")
                        .HasForeignKey("MediaFormatId");
                });
#pragma warning restore 612, 618
        }
    }
}
